version: 2.1
jobs:
  hello-world:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Print Hello World
          command: echo 'Hello, World!'
workflows:
  version: 2
  hello-world-workflow:
    jobs:
      - hello-world